### ISSUE TITLE
creating links / symlinks doesn't work on Android

### ISSUE THREAD

**Issue by HJarausch** [mpartel/bindfs#96] opened 2021-02-14 19:32 UTC
I am not sure it is a bug, but I am missing something.
On Termux (Android), I have created a file and made an ext4 FS on it. I created a loop device with **losetup** and I mounted it on /mnt/TermuX (just a name). Afterwards I used
``bindfs -u 10218 -g 10218 /mnt/TermuX  /data/data/termux.com/files/home/TermuX``

As normal user (uid=10218) I can created, remove files. But an **ln** or **ln -s** produces a permission problem.

What am I missing or is it a bug.

**Comment by mpartel** [comment] 2021-02-15 03:20
Strange.
- Could you add `-d` to bindfs and see whether it gets `opcode: SYMLINK` and what is printed after it?
- Does manually symlinking in the source directory as the user that ran the `bindfs` command (root?) work?

**Comment by HJarausch** [comment] 2021-02-15 16:38
Thanks for your help.
I've tried that:  bindfs -d -u10218 -g10218 /mnt/TermuX  /data/data/com/termux/files/home/TermuX

In another terminal, within /data/data/com/termux/files/home I did
pushd TermuX
ln -s build_nim xxx

This gave the following log (in the other window)
unique: 24, opcode: GETATTR (3), nodeid: 1, insize: 5
6, pid: 11628
getattr /
unique: 24, success, outsize: 120
unique: 25, opcode: GETXATTR (22), nodeid: 1, insize:
68, pid: 11628
getxattr / security.capability 20
unique: 25, error: -61 (No data available), outsiz
e: 16
unique: 26, opcode: OPENDIR (27), nodeid: 1, insize:
48, pid: 11628
unique: 26, success, outsize: 32
unique: 27, opcode: READDIR (28), nodeid: 1, insize:
80, pid: 11628
readdir[0] from 0
unique: 27, success, outsize: 312
unique: 28, opcode: READDIR (28), nodeid: 1, insize:
80, pid: 11628
unique: 28, success, outsize: 16
unique: 29, opcode: RELEASEDIR (29), nodeid: 1, insiz
e: 64, pid: 0
unique: 29, success, outsize: 16
unique: 30, opcode: GETXATTR (22), nodeid: 1, insize:
68, pid: 10214
getxattr / security.capability 20
unique: 30, error: -61 (No data available), outsize: 16
unique: 31, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 10214
getattr /
unique: 31, success, outsize: 120
unique: 32, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid 10214
LOOKUP /build_nim
getattr /build_nim
NODEID: 5
unique: 32, success, outsize: 144
unique: 33, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 10214
getxattr /build_nim security.capability 20
unique: 33, error: -61 (No data available), outsize: 16
unique: 34, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 10214
getxattr /build_nim security.capability 20
unique: 34, error: -61 (No data available), outsize: 16
unique: 35, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 11631
getattr /
unique: 35, success, outsize: 120
unique: 36, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 11631
LOOKUP /build_nim
getattr /build_nim
NODEID: 5
unique: 36, success, outsize: 144
unique: 37, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 11631
getxattr /build_nim security.capability 20
unique: 37, error: -61 (No data available), outsize: 16
unique: 38, opcode: GETXATTR (22), nodeid: 1, insize:
68, pid: 11631
getxattr / security.capability 20
unique: 38, error: -61 (No data available), outsize: 16
unique: 39, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid:11631
LOOKUP /xxx
getattr /xxx
unique: 39, error: -2 (No such file or directory), outsize: 16
unique: 40, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 11631
getxattr /build_nim security.capability 20
unique: 40, error: -61 (No data available), outsize: 16

**Comment by mpartel** [comment] 2021-02-16 02:10
It looks like bindfs never gets the `SYMLINK` request, so it seems unlikely that this is a bindfs bug.

More likely it's something to do with libfuse and Android's kernel. I know some Androids are stuck on pretty ancient kernels, or perhaps it's libfuse that's out of date. 

Debugging this is likely to be difficult, but you can at least run `strace ln -s ...` to check whether it's the `symlink` syscall that's giving you the `EPERM`. If it's not, that'd be an interesting hint.

Also, have you checked that you can successfully `ln -s` on the underlying FS i.e. without bindfs (and probably as root)?

**Comment by HJarausch** [comment] 2021-02-16 13:34
On 02/16/2021 03:10:24 AM, Martin Pärtel wrote:
> Hi Martin (are you speaking German)
Thanks for your help.

I have attached the (xz-compressed) output of strace.

I suspect it is a SELinux context problem.

ls -Zd /data/data/com.termux/files/home
    gives  u:object_r:app_data_file:s0:c128,c256,c512,c768

while
ls -Zd /data/data/com.termux/files/home/TermuX  (the destination of  
bindfs)
   gives u:object_r:fuse:s0

I have no knowledge about SELinux context, but it looks different.

Is there any means to set the SELinux context with bindfs?

Does it work on SELinux systems at all?

Many thanks again,
Helmut

**Comment by mpartel** [comment] 2021-02-17 03:15
I did not get the attachment. Github seems to have eaten it :/

Unfortunately I know next to nothing about SELinux, so I have no idea how it might interact with bindfs/FUSE. [This](https://github.com/libfuse/libfuse/issues/36) suggests there might be problems with libfuse 2.9.6 or older. bindfs does forward extended attributes by default, but I don't know if that's enough.

**Comment by HJarausch** [comment] 2021-02-17 16:46
Now I have tried with libfuse-3.10.1 and bindfs-1.15.0
As normal user I changed directory to the destination directory of *bindfs*.
There is a file *build_nim*. I issued the command ``ln -s build_nim xxx``.
Here is the output of  **bindfs -d ...**

``
unique: 37, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1584
getattr[NULL] /

unique: 37, success, outsize: 120
unique: 38, opcode: GETXATTR (22), nodeid: 1, insize: 68, pid: 1584
getxattr / security.capability 20

unique: 38, error: -61 (No data available), outsize: 16
unique: 39, opcode: GETATTR (3), nodeid: 1, insize: 56, pid:1584
getattr[NULL] /

unique: 39, success, outsize: 120
unique: 40, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 1584

unique: 40, success, outsize: 32
unique: 41, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 1584
readdir[0] from 0

unique: 41, success, outsize: 312
unique: 42, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 1584

unique: 42, success, outsize: 16
unique: 43, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0

unique: 43, success, outsize: 16
unique: 44, opcode: GETXATTR (22), nodeid: 1, insize:68, pid: 27137
getxattr / security.capability 20

unique: 44, error: -61 (No data available), outsize: 16
unique: 45, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 27137
getattr[NULL] /

unique: 45, success, outsize: 120
unique: 46, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 27137

getattr[NULL] /

unique: 46, success, outsize: 120
unique: 47, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 27137
LOOKUP /build_nim
getattr[NULL] /build_nim

NODEID: 5

unique: 47, success, outsize: 144
unique: 48, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 27137
getxattr /build_nim security.capability 20

unique: 48, error: -61 (No data available), outsize: 16

unique: 49, opcode: GETATTR (3), nodeid: 5, insize: 56, pid: 27137
getattr[NULL] /build_nim

unique: 49, success, outsize: 120
unique: 50, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 27137
getattr[NULL] /

unique: 50, success, outsize: 120
unique: 51, opcode: LOOKUP (1), nodeid: 1, insize: 50, pid: 27137
LOOKUP /build_nim
getattr[NULL] /build_nim

NODEID: 5

unique: 51, success, outsize: 144
unique: 52, opcode: GETXATTR (22), nodeid: 5, insize: 68, pid: 27137
getxattr /build_nim security.capability 20

unique: 52, error: -61 (No data available), outsize: 16
unique: 53, opcode: GETATTR (3), nodeid: 5, insize: 56, pid: 27137
getattr[NULL] /build_nim

unique: 53, success, outsize: 120
unique: 54, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1589

unique: 54, success, outsize: 120
unique: 55, opcode: GETXATTR (22), nodeid: 1, insize: 68, pid: 1589
getxattr / security.capability 20

unique: 55, error: -61 (No data available), outsize: 16
unique: 56, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 1589
LOOKUP /xxx
getattr[NULL] /xxx

unique: 56, error: -2 (No such file or directory), outsize: 16
unique: 57, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1589
getattr[NULL] /

unique: 54, success, outsize: 120
unique: 55, opcode: GETXATTR (22), nodeid: 1, insize: 68, pid: 1589
getxattr / security.capability 20

unique: 55, error: -61 (No data available), outsize: 16
unique: 56, opcode: LOOKUP (1), nodeid: 1, insize: 44, pid: 1589
LOOKUP /xxx
getattr[NULL] /xxx

unique: 56, error: -2 (No such file or directory), outsize: 16
unique: 57, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 1589
getattr[NULL] /

unique: 57, success, outsize: 120

``

**Comment by HJarausch** [comment] 2021-02-17 17:01
And here the final part of *strace*

``
write(2, "unique: 11, opcode: READDIR (28)"..., 67) = 67
write(2, "   unique: 11, success, outsize:"..., 36) = 36
writev(4, [{iov_base="\20\0\0\0\0\0\0\0\v\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "@\0\0\0\35\0\0\0\f\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 135168) = 64
write(2, "unique: 12, opcode: RELEASEDIR ("..., 67) = 67
write(2, "   unique: 12, success, outsize:"..., 36) = 36
writev(4, [{iov_base="\20\0\0\0\0\0\0\0\f\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "D\0\0\0\26\0\0\0\r\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 13, opcode: GETXATTR (22"..., 69) = 69
write(2, "getxattr / security.capability 2"..., 34) = 34
lgetxattr(".", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 13, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\r\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\16\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 14, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 14, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\16\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "8\0\0\0\3\0\0\0\17\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 15, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 15, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\17\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "2\0\0\0\1\0\0\0\20\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 50
write(2, "unique: 16, opcode: LOOKUP (1), "..., 66) = 66
write(2, "LOOKUP /build_nim\n", 18)     = 18
write(2, "getattr[NULL] /build_nim\n", 25) = 25
fstatat64(AT_FDCWD, "build_nim", {st_mode=S_IFREG|0700, st_size=597, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   NODEID: 2\n", 13)          = 13
write(2, "   unique: 16, success, outsize:"..., 37) = 37
writev(4, [{iov_base="\220\0\0\0\0\0\0\0\20\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
read(4, "D\0\0\0\26\0\0\0\21\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 17, opcode: GETXATTR (22"..., 69) = 69
write(2, "getxattr /build_nim security.cap"..., 43) = 43
lgetxattr("build_nim", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 17, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\21\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\22\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 18, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /build_nim\n", 25) = 25
fstatat64(AT_FDCWD, "build_nim", {st_mode=S_IFREG|0700, st_size=597, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 18, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\22\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\f\0\0\0\0\0\0\0U\2\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "8\0\0\0\3\0\0\0\23\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 19, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 19, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\23\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "2\0\0\0\1\0\0\0\24\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 50
write(2, "unique: 20, opcode: LOOKUP (1), "..., 66) = 66
write(2, "LOOKUP /build_nim\n", 18)     = 18
write(2, "getattr[NULL] /build_nim\n", 25) = 25
fstatat64(AT_FDCWD, "build_nim", {st_mode=S_IFREG|0700, st_size=597, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   NODEID: 2\n", 13)          = 13
write(2, "   unique: 20, success, outsize:"..., 37) = 37
writev(4, [{iov_base="\220\0\0\0\0\0\0\0\24\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., iov_len=128}], 2) = 144
read(4, "D\0\0\0\26\0\0\0\25\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 21, opcode: GETXATTR (22"..., 69) = 69
write(2, "getxattr /build_nim security.cap"..., 43) = 43
lgetxattr("build_nim", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 21, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\25\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\26\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 22, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /build_nim\n", 25) = 25
fstatat64(AT_FDCWD, "build_nim", {st_mode=S_IFREG|0700, st_size=597, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 22, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\26\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\f\0\0\0\0\0\0\0U\2\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "8\0\0\0\3\0\0\0\27\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 23, opcode: GETATTR (3),"..., 66) = 66
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 23, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\27\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "D\0\0\0\26\0\0\0\30\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 24, opcode: GETXATTR (22"..., 68) = 68
write(2, "getxattr / security.capability 2"..., 34) = 34
lgetxattr(".", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 24, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\30\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, ",\0\0\0\1\0\0\0\31\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 44
write(2, "unique: 25, opcode: LOOKUP (1), "..., 65) = 65
write(2, "LOOKUP /xxx\n", 12)           = 12
write(2, "getattr[NULL] /xxx\n", 19)    = 19
fstatat64(AT_FDCWD, "xxx", 0xbe81b900, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory)
write(2, "   unique: 25, error: -2 (No suc"..., 66) = 66
writev(4, [{iov_base="\20\0\0\0\376\377\377\377\31\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\32\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 26, opcode: GETATTR (3),"..., 66) = 66
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 26, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\32\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "D\0\0\0\26\0\0\0\33\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 27, opcode: GETXATTR (22"..., 69) = 69
write(2, "getxattr / security.capability 2"..., 34) = 34
lgetxattr(".", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 27, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\33\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\34\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 28, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 28, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\34\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, "D\0\0\0\26\0\0\0\35\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 68
write(2, "unique: 29, opcode: GETXATTR (22"..., 69) = 69
write(2, "getxattr / security.capability 2"..., 34) = 34
lgetxattr(".", "security.capability", 0xb4d06078, 20) = -1 ENODATA (No data available)
write(2, "   unique: 29, error: -61 (No da"..., 59) = 59
writev(4, [{iov_base="\20\0\0\0\303\377\377\377\35\0\0\0\0\0\0\0", iov_len=16}], 1) = 16
read(4, "8\0\0\0\3\0\0\0\36\0\0\0\0\0\0\0\1\0\0\0\0\0\0\0\352'\0\0\352'\0\0"..., 135168) = 56
write(2, "unique: 30, opcode: GETATTR (3),"..., 67) = 67
write(2, "getattr[NULL] /\n", 16)       = 16
fstatat64(AT_FDCWD, ".", {st_mode=S_IFDIR|0700, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
write(2, "   unique: 30, success, outsize:"..., 37) = 37
writev(4, [{iov_base="x\0\0\0\0\0\0\0\36\0\0\0\0\0\0\0", iov_len=16}, {iov_base="\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\2\0\0\0\0\0\0\0\0\20\0\0\0\0\0\0"..., iov_len=104}], 2) = 120
read(4, 0xb4a908c0, 135168)             = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
sigreturn({mask=[RTMIN]})               = -1 EINTR (Interrupted system call)
madvise(0xb4a90000, 1314816, MADV_DONTNEED) = 0
rt_sigaction(SIGHUP, NULL, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGTERM, NULL, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, {sa_handler=0xb4fa2dc1, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGPIPE, NULL, {sa_handler=0xb4fa2df5, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, {sa_handler=0xb4fa2df5, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0xb50bcca8}, 8) = 0
ppoll([{fd=4, events=0}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 0 (Timeout)
close(4)                                = 0
geteuid32()                             = 0
fstatat64(AT_FDCWD, "/proc/mounts", {st_mode=S_IFLNK|0777, st_size=11, ...}, AT_SYMLINK_NOFOLLOW) = 0
umount2("/data/data/com.termux/files/home/TermuX", MNT_DETACH) = 0
munmap(0xb52b5000, 4096)                = 0
close(3)                                = 0
mprotect(0xb5457000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xb5457000, 4096, PROT_READ)   = 0
mprotect(0xb5457000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xb5457000, 4096, PROT_READ)   = 0
mprotect(0xb5457000, 4096, PROT_READ|PROT_WRITE) = 0
mprotect(0xb5457000, 4096, PROT_READ)   = 0
munmap(0xb5457000, 4096)                = 0
exit_group(7)                           = ?
+++ exited with 7 +++
``

**Comment by mpartel** [comment] 2021-02-19 02:39
That looks like an strace of `bindfs` but I was thinking of stracing `ln -s`.

**Comment by HJarausch** [comment] 2021-02-19 19:21
[ln.strace.xz.txt](https://github.com/mpartel/bindfs/files/6012464/ln.strace.xz.txt)

Here is the strace output for 'ln -s build_nim xxx'.

Please decode the attached file with base64 -d   and then decompress with xz -d.
Sorry for the inconvenience.
Thanks for looking into it,
Helmut

**Comment by mpartel** [comment] 2021-02-20 12:32
Unfortunately it's as expected:

    symlinkat("build_nim", AT_FDCWD, "xxx") = -1 EACCES (Permission denied)

So `ln` makes the symlink request to the kernel but the kernel denies the request before sending it to bindfs. I don't know why it would do that.

`man symlinkat` documents the error like this:

>        EACCES Write access to the directory containing linkpath is denied, or one of the directories in the path pre‐
>               fix of linkpath did not allow search permission.  (See also path_resolution(7).)

I also noticed this suspicious line:

    faccessat(AT_FDCWD, "/data", R_OK)      = -1 EACCES (Permission denied)

That seems to mean that the `ln` process doesn't have "search permission" on `/data`, and your mountpoint is below `/data` :thinking: 

So my guess is still some Android-specific security/sandboxing feature being weird, but I don't have any concrete ideas on how to debug further, sorry.

I'm closing this since it appears to not be a bindfs bug, but feel free to continue discussion if you find something new. If you find the root cause, I'd love to hear about it!

**Closed by mpartel** 2021-02-20 12:32 UTC
Labels: support
